version: '3'

networks:
  image_classifier_network:
    driver: bridge
 
services:
  api:
    image: hunch.azurecr.io/hunch-image-classifier-api:latest
    #build: .
    command: sh -c "uvicorn app.main:app --port=8003 --host=0.0.0.0 --workers=1"
    deploy:
      replicas: 8
    networks:
      - image_classifier_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    ports:
      - 8003:8003
    networks:
      - image_classifier_network