version: '3'

services:
  api:
    # container_name: lifestyle_classifier
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    # command: tail -f /dev/null
    
    # deploy:
    #   replicas: 8

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - api
  #   ports:
  #     - 8003:8003
  #   networks:
  #     - image_classifier_network